version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - PLEX_CLAIM=claim-2d_RdBntB3ydVkyk_yW6
    network_mode: host
    volumes:
      - ~/plex/database:/config
      - ~/plex/transcode:/transcode
      - /mnt/media1/media:/data
      - /mnt/media2/media:/data2
